# Generated by Django 5.1.7 on 2025-03-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outro', 'Outro'), ('Prefiro não declarar', 'Prefiro não declarar')], max_length=20)),
                ('idade', models.CharField(choices=[('18 a 35', '18 a 35'), ('36 a 50', '36 a 50'), ('51 a 65', '51 a 65'), ('+ de 66', '+ de 66')], max_length=10)),
                ('frequencia_compra', models.CharField(choices=[('2x semana', '2x semana'), ('1x semana', '1x semana'), ('Todo dia', 'Todo dia'), ('2x mês', '2x mês'), ('1x mês', '1x mês')], max_length=10)),
                ('gasto_medio', models.CharField(choices=[('400 ou +', '400 ou +'), ('350 a 400', '350 a 400'), ('300 a 350', '300 a 350'), ('250 a 300', '250 a 300'), ('200 a 250', '200 a 250'), ('150 a 200', '150 a 200'), ('100 a 150', '100 a 150'), ('até 100', 'até 100')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
