# Generated by Django 5.1.7 on 2025-03-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesquisa',
            name='created_at',
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='avaliacao_atendimento',
            field=models.CharField(choices=[('Bom', 'Bom'), ('Muito bom', 'Muito bom'), ('Ruim', 'Ruim'), ('Regular', 'Regular')], default='regular', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='avaliacao_limpeza',
            field=models.CharField(choices=[('Bom', 'Bom'), ('Muito bom', 'Muito bom'), ('Ruim', 'Ruim'), ('Regular', 'Regular')], default='regular', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='avaliacao_preços',
            field=models.CharField(choices=[('Bom', 'Bom'), ('Muito bom', 'Muito bom'), ('Ruim', 'Ruim'), ('Regular', 'Regular')], default='otimo', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='avaliacao_variedade',
            field=models.CharField(choices=[('Bom', 'Bom'), ('Muito bom', 'Muito bom'), ('Ruim', 'Ruim'), ('Regular', 'Regular')], default='otimo', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='canal_radio',
            field=models.CharField(choices=[('Melodia', 'Melodia'), ('Tupi', 'Tupi'), ('FM O Dia', 'FM O Dia'), ('Rádio Mix', 'Rádio Mix'), ('Band News', 'Band News'), ('MPB FM', 'MPB FM'), ('CBN', 'CBN'), ('Transamérica', 'Transamérica'), ('Outro', 'Outro'), ('Nenhum', 'Nenhum')], default='radio', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='canal_tv',
            field=models.CharField(choices=[('Globo', 'Globo'), ('Record', 'Record'), ('SBT', 'SBT'), ('Band', 'Band'), ('RedeTV', 'RedeTV'), ('Outro', 'Outro'), ('Nenhum', 'Nenhum')], default='tv', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='fatores_escolha',
            field=models.CharField(choices=[('Preço', 'Preço'), ('Promoções', 'Promoções'), ('Qualidade', 'Qualidade'), ('Marca', 'Marca'), ('Sustentabilidade', 'Sustentabilidade'), ('Proximidade', 'Proximidade'), ('Atendimento', 'Atendimento'), ('Possibilidade de realizar as compras de forma online', 'Possibilidade de realizar as compras de forma online')], default='melhor', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='loja_redeconomia',
            field=models.CharField(choices=[('Redeconomia Alfa e Omega', 'Redeconomia Alfa e Omega'), ('Redeconomia Reunidos', 'Redeconomia Reunidos'), ('Redeconomia Mix Certo', 'Redeconomia Mix Certo'), ('Redeconomia Feira Nova', 'Redeconomia Feira Nova'), ('Redeconomia Flor da Posse', 'Redeconomia Flor da Posse'), ('Redeconomia Emanuel', 'Redeconomia Emanuel'), ('Redeconomia Polisuper', 'Redeconomia Polisuper'), ('Redeconomia Celeiro', 'Redeconomia Celeiro'), ('Redeconomia Super Pax', 'Redeconomia Super Pax'), ('Redeconomia CAB', 'Redeconomia CAB'), ('Redeconomia Campeão', 'Redeconomia Campeão'), ('Redeconomia Cariocão', 'Redeconomia Cariocão'), ('Redeconomia Principal', 'Redeconomia Principal'), ('Redeconomia Superprix', 'Redeconomia Superprix'), ('Redeconomia Princesa', 'Redeconomia Princesa'), ('Redeconomia Magé', 'Redeconomia Magé'), ('Redeconomia Mix Certo', 'Redeconomia Mix Certo')], default='rio', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='meios_deacompanhamento',
            field=models.CharField(choices=[('Site', 'Site'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Youtube', 'Youtube'), ('Tiktok', 'Tiktok'), ('Canal do Whatsapp', 'Canal do Whatsapp'), ('Televisão', 'Televisão'), ('Rádio', 'Rádio'), ('Lojas físicas', 'Lojas físicas'), ('Não acompanho ofertas e novidades da Redeconomia', 'Não acompanho ofertas e novidades da Redeconomia')], default='email', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='motivos_redeconomia',
            field=models.CharField(choices=[('Promoção', 'Promoção'), ('Preço', 'Preço'), ('Proximidade', 'Proximidade'), ('Variedade', 'Variedade'), ('Qualidade', 'Qualidade'), ('Atendimento', 'Atendimento'), ('Outros', 'Outros')], default='preco', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='outras_lojas',
            field=models.CharField(choices=[('Outros', 'Outros'), ('Inter', 'Inter'), ('Zona Sul', 'Zona Sul'), ('Assaí', 'Assaí'), ('Princesa', 'Princesa'), ('Carrefour', 'Carrefour'), ('Unidos', 'Unidos'), ('Extra', 'Extra'), ('Multi Market', 'Multi Market'), ('Prezunic', 'Prezunic'), ('Mundial', 'Mundial'), ('Supermarket', 'Supermarket'), ('Guanabara', 'Guanabara'), ('Vianense', 'Vianense'), ('Campeao', 'Campeão')], default='otima', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='pontos_negativos',
            field=models.CharField(choices=[('Preço', 'Preço'), ('Qualidade', 'Qualidade'), ('Limpeza', 'Limpeza'), ('Atendimento', 'Atendimento'), ('Variedade', 'Variedade'), ('Localização', 'Localização'), ('Conforto', 'Conforto'), ('Padaria', 'Padaria'), ('Hortifruti', 'Hortifruti'), ('Outro', 'Outro')], default='nda', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='pontos_positivos',
            field=models.CharField(choices=[('Preço', 'Preço'), ('Qualidade', 'Qualidade'), ('Limpeza', 'Limpeza'), ('Atendimento', 'Atendimento'), ('Variedade', 'Variedade'), ('Localização', 'Localização'), ('Conforto', 'Conforto'), ('Padaria', 'Padaria'), ('Hortifruti', 'Hortifruti'), ('Outro', 'Outro')], default='a', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='principais_motivos',
            field=models.CharField(choices=[('Promoção', 'Promoção'), ('Preço', 'Preço'), ('Proximidade', 'Proximidade'), ('Variedade', 'Variedade'), ('Qualidade', 'Qualidade'), ('Cartão', 'Cartão'), ('Vantagens do aplicativo', 'Vantagens do aplicativo')], default='a', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='produtos_anunciados',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='a', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='sugestoes_melhorias',
            field=models.CharField(choices=[('Melhorar os preços', 'Melhorar os preços'), ('Oferecer mais promoções', 'Oferecer mais promoções'), ('Ampliar a variedade de produtos', 'Ampliar a variedade de produtos'), ('Melhorar o atendimento', 'Melhorar o atendimento'), ('Vendas online', 'Vendas online'), ('Outro', 'Outro')], default='a', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='uso_app',
            field=models.CharField(choices=[('Não conheço o APP', 'Não conheço o APP'), ('Já ouvi falar mas nunca baixei', 'Já ouvi falar mas nunca baixei'), ('Já baixei o APP mas nunca usei', 'Já baixei o APP mas nunca usei'), ('Uso as vezes', 'Uso as vezes'), ('Uso em todas as minhas compras', 'Uso em todas as minhas compras')], default='a', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='gasto_medio',
            field=models.CharField(choices=[('400 ou +', '400 ou +'), ('350 a 400', '350 a 400'), ('300 a 350', '300 a 350'), ('250 a 300', '250 a 300'), ('200 a 250', '200 a 250'), ('150 a 200', '150 a 200'), ('100 a 150', '100 a 150'), ('até 100', 'até 100')], max_length=15),
        ),
    ]
