# Generated by Django 5.1.7 on 2025-03-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0002_remove_pesquisa_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='loja_redeconomia',
            field=models.CharField(choices=[('Redeconomia Alfa e Omega', 'Redeconomia Alfa e Omega'), ('Redeconomia Reunidos', 'Redeconomia Reunidos'), ('Redeconomia Mix Certo', 'Redeconomia Mix Certo'), ('Redeconomia Feira Nova Nilópolis ', 'Redeconomia Feira Nova Nilópolis '), ('Redeconomia Feira Nova Parque, Queimados ', 'Redeconomia Feira Nova Parque, Queimados '), ('Redeconomia Flor da Posse Teresópolis ', 'Redeconomia Flor da Posse Teresópolis '), ('Redeconomia Flor da Posse Guapimirim', 'Redeconomia Flor da Posse Guapimirim'), ('Redeconomia Emanuel Pedra de Guaratiba', 'Redeconomia Emanuel Pedra de Guaratiba'), ('Redeconomia Emanuel Campo Grande', 'Redeconomia Emanuel Campo Grande'), ('Redeconomia Polisuper', 'Redeconomia Polisuper'), ('Redeconomia Celeiro', 'Redeconomia Celeiro'), ('Redeconomia Super Pax Realengo', 'Redeconomia Super Pax Realengo'), ('Redeconomia Super Pax Vila da Penha', 'Redeconomia Super Pax Vila da Penha'), ('Redeconomia Super Pax Rio de Janeiro', 'Redeconomia Super Pax Rio de Janeiro'), ('Redeconomia Super Pax Del Castilho', 'Redeconomia Super Pax Del Castilho'), ('Redeconomia CAB', 'Redeconomia CAB'), ('Redeconomia Campeão Barra da Tijuca', 'Redeconomia Campeão Barra da Tijuca'), ('Redeconomia Campeão Madureira', 'Redeconomia Campeão Madureira'), ('Redeconomia Campeão Centro, Nova Iguaçu', 'Redeconomia Campeão Centro, Nova Iguaçu'), ('Redeconomia Cariocão', 'Redeconomia Cariocão'), ('Redeconomia Principal', 'Redeconomia Principal'), ('Redeconomia Superprix', 'Redeconomia Superprix'), ('Redeconomia Princesa Arraial do Cabo', 'Redeconomia Princesa Arraial do Cabo'), ('Redeconomia Princesa Copacabana', 'Redeconomia Princesa Copacabana'), ('Redeconomia Princesa Laranjeiras', 'Redeconomia Princesa Laranjeiras'), ('Redeconomia Magé', 'Redeconomia Magé'), ('Redeconomia Mix Certo', 'Redeconomia Mix Certo')], max_length=50),
        ),
    ]
