# Generated by Django 5.1.7 on 2025-03-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0003_alter_pesquisa_loja_redeconomia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='colaboradora',
            field=models.CharField(choices=[('Tábata', 'Tábata'), ('Raquel', 'Raquel'), ('Melissa', 'Melissa'), ('Carina', 'Carina'), ('Camila', 'Camila')], default='A', max_length=50),
            preserve_default=False,
        ),
    ]
